"""empty message

Revision ID: b50a9c660575
Revises: 6c2c15275414
Create Date: 2023-08-02 15:00:59.430163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50a9c660575'
down_revision = '6c2c15275414'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('bpocket', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('closure', sa.String(), nullable=True))
    op.add_column('product', sa.Column('collar', sa.String(), nullable=True))
    op.add_column('product', sa.Column('fabric', sa.String(), nullable=True))
    op.add_column('product', sa.Column('length', sa.String(), nullable=True))
    op.add_column('product', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('product', sa.Column('pockets', sa.String(), nullable=True))
    op.add_column('product', sa.Column('size', sa.String(), nullable=True))
    op.drop_column('product', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('product', 'size')
    op.drop_column('product', 'pockets')
    op.drop_column('product', 'notes')
    op.drop_column('product', 'length')
    op.drop_column('product', 'fabric')
    op.drop_column('product', 'collar')
    op.drop_column('product', 'closure')
    op.drop_column('product', 'bpocket')
    # ### end Alembic commands ###
